data:
  train_files: /data/zhouwenkang/FAST/train_data/ViRL39K/virl39k_train.json
  val_files:
    - /data/zhouwenkang/FAST/val_data/MMK12/mmk12_test.json
  val_names:
    - MMK12
  prompt_key: question
  answer_key: answer
  image_key: image
  video_key: videos
  image_dir: /data/zhouwenkang/FAST/train_data/ViRL39K
  video_fps: 2.0
  max_prompt_length: 4096
  max_response_length: 4096
  rollout_batch_size: 512
  mini_rollout_batch_size: 8
  val_batch_size: 512
  format_prompt: examples/format_prompt/math.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 1000000
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: false
  filter_key: accuracy
  filter_low: 0.01
  filter_high: 0.99
  dynamic_filter_schedule:
    - epoch_ratio: 0.5
      filter_low: 0.01
      filter_high: 0.7
    - epoch_ratio: 1.0
      filter_low: 0.3
      filter_high: 0.99
  hperc_filter_schedule:
    - epoch_ratio: 0.3
      hperc_high: 0.55
    - epoch_ratio: 0.7
      hperc_high: 0.85
    - epoch_ratio: 1.0
      hperc_high: 0.99
  kl_type: "fixed"
  kl_min_coef: 0.001
  kl_max_coef: 0.03
  tau_perc: 0.5

worker:
  actor:
    global_batch_size: 8
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 1
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: /data/zhouwenkang/models/Qwen2.5-VL-3B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    n: 8
    temperature: 1.0
    top_p: 1.0
    limit_images: 0
    gpu_memory_utilization: 0.5
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    disable_tqdm: false
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: true

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/perceptgate_reward.py:compute_score

trainer:
  total_epochs: 10
  max_steps: null
  project_name: perceptgate
  experiment_name: pg-step3-3b
  logger: ["file", "tensorboard", "wandb"]
  nnodes: 1
  n_gpus_per_node: 4
  max_try_make_batch: -1
  val_freq: 10
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 10
  save_limit: -1
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
